import 'package:flutter/material.dart';
import 'services/sentence_generator.dart';
import 'exercise_screen.dart';

class CriteriaInputScreen extends StatefulWidget {
  final String selectedLanguage;

  const CriteriaInputScreen({
    required this.selectedLanguage,
    Key? key,
  }) : super(key: key);

  @override
  _CriteriaInputScreenState createState() => _CriteriaInputScreenState();
}

class _CriteriaInputScreenState extends State<CriteriaInputScreen> {
  String _level = 'Beginner';
  final _topicController = TextEditingController();
  final _dictionaryController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Learning Criteria'),
        backgroundColor: Colors.blue,
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            DropdownButtonFormField(
              value: _level,
              items: ['Beginner', 'Intermediate', 'Advanced']
                  .map((level) => DropdownMenuItem(
                        value: level,
                        child: Text(level),
                      ))
                  .toList(),
              onChanged: (value) => setState(() => _level = value.toString()),
              decoration: const InputDecoration(
                labelText: 'Skill Level',
                border: OutlineInputBorder(),
              ),
            ),
            const SizedBox(height: 20),
            TextField(
              controller: _topicController,
              decoration: const InputDecoration(
                labelText: 'Topics (comma-separated)',
                border: OutlineInputBorder(),
              ),
            ),
            const SizedBox(height: 20),
            TextField(
              controller: _dictionaryController,
              decoration: const InputDecoration(
                labelText: 'Focus Words (comma-separated)',
                border: OutlineInputBorder(),
              ),
            ),
            const SizedBox(height: 30),
            ElevatedButton(
              onPressed: _generateExercises,
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.blue, // Fixed parameter
                padding: const EdgeInsets.symmetric(
                    horizontal: 30, vertical: 15),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
              ),
              child: const Text(
                'Generate Exercises',
                style: TextStyle(
                    fontSize: 18,
                    color: Colors.white),
              ),
            ),
          ],
        ),
      ),
    );
  }

  void _generateExercises() async {
    final criteria = {
      'language': widget.selectedLanguage,
      'level': _level,
      'topics': _topicController.text,
      'dictionary': _dictionaryController.text,
    };

    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => const AlertDialog(
        title: Text('Generating Exercises'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            CircularProgressIndicator(),
            SizedBox(height: 20),
            Text('This may take 10-20 seconds...'),
          ],
        ),
      ),
    );

    try {
      final sentences = await SentenceGenerator.generateSentences(criteria);
      Navigator.pop(context);
      
      if (sentences.isEmpty) {
        throw Exception('No sentences generated by the AI');
      }

      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) => ExerciseScreen(
            sentences: sentences,
            targetLanguage: widget.selectedLanguage,
          ),
        ),
      );
    } catch (e) {
      Navigator.pop(context);
      showDialog(
        context: context,
        builder: (context) => AlertDialog(
          title: const Text('Error'),
          content: Text('Failed to generate exercises:\n$e'),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('OK'),
            )
          ],
        ),
      );
    }
  }
}